Repository 202306-NEA-DZ-FEW/online-Therapist, pull requests merged in 2023-10, with the labels that each got.

#9 Set up project structure
  src/components/Footer/Footer.jsx
  src/components/Footer/__test__/Footer.test.js
  src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/__test__/Navbar.test.js
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/layout/Layout.jsx
Labels: enhancement, structure

#37 feat(deploy to netlify): deployement of the project to Netlify
  README.md
Labels: enhancement, deploy

#40 feat(components/suggestedblogscard): add suggested blogs card component
  public/blog-img-placeholder.svg
  src/components/Blog/SuggestedBlogsCard/Card.jsx
Labels: enhancement, component

#41 feat(components/home/areyoucouncelor): add are you a councelor section as a component
  src/components/Home/AreYouCouncelor.jsx
  src/components/Home/__test__/AreYouCouncelor.test.js
  src/components/Home/__test__/__snapshots__/AreYouCouncelor.test.js.snap
Labels: enhancement, component, feature

#47 create a hero section as slide show
  next.config.js
  package-lock.json
  package.json
  src/components/Home/HeroSection.jsx
  src/components/Home/__test__/HeroSection.test.js
  src/components/Home/__test__/__snapshots__/HeroSection.test.js.snap
  src/components/Home/__test__/matchMedia.mock.js
  src/components/elements/Buttons/Button.jsx
  src/pages/index.jsx
  src/util/library.js
  tailwind.config.js
  test-setup.js
Labels: enhancement, help wanted, design, component

#48 create an appointement section
  src/components/Home/AppointmentSection.jsx
  src/components/Home/__test__/AppointementSection.test.js
  src/components/Home/__test__/__snapshots__/AppointementSection.test.js.snap
  src/pages/index.jsx
  tailwind.config.js
Labels: enhancement, help wanted, design, component

#49 create communication section
  src/components/Cards/CommunicationCard.jsx
  src/components/Cards/__test__/CommunicationCard.test.js
  src/components/Cards/__test__/__snapshots__/CommunicationCard.test.js.snap
  src/components/Home/CommunicationSection.jsx
  src/components/Home/__test__/CommunicationSection.test.js
  src/components/Home/__test__/__snapshots__/CommunicationSection.test.js.snap
  src/pages/index.jsx
  tailwind.config.js
Labels: enhancement, help wanted, design, component

#51 creat navbar component
  .husky/pre-commit
  public/close.svg
  public/hamburger-menu.svg
  public/locales/ar/common.json
  public/locales/en/common.json
  public/logo.png
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/context/context.js
  src/layout/Layout.jsx
Labels: enhancement, component

#42 add purchase tickets and are you councelor sections
  src/components/Home/AreYouCouncelor.jsx
  src/components/Home/TicketCard.jsx
  src/components/Home/TicketsSection.jsx
  src/components/Home/__test__/AreYouCouncelor.test.js
  src/components/Home/__test__/TicketCard.test.js
  src/components/Home/__test__/TicketsSection.test.js
  src/components/Home/__test__/__snapshots__/AreYouCouncelor.test.js.snap
  src/components/Home/__test__/__snapshots__/TicketCard.test.js.snap
  src/components/Home/__test__/__snapshots__/TicketsSection.test.js.snap
Labels: enhancement, help wanted, component, feature

#56 Create contact and contactThankYou page
  public/Contact.jpg
  src/pages/contact.jsx
  src/pages/contactThankYou.jsx
Labels: design, page, feature

#57 12 home page
  next.config.js
  package-lock.json
  package.json
  public/blog-img-placeholder.svg
  src/components/Blog/SuggestedBlogsCard/Card.jsx
  src/components/Blog/SuggestedBlogsCard/__test__/Card.test.js
  src/components/Blog/SuggestedBlogsCard/__test__/__snapshots__/Card.test.js.snap
  src/components/Cards/CommunicationCard.jsx
  src/components/Cards/TicketCard.jsx
  src/components/Cards/__test__/CommunicationCard.test.js
  src/components/Cards/__test__/TicketCard.test.js
  src/components/Cards/__test__/__snapshots__/CommunicationCard.test.js.snap
  src/components/Cards/__test__/__snapshots__/TicketCard.test.js.snap
  src/components/Home/AppointmentSection.jsx
  src/components/Home/AreYouCouncelor.jsx
  src/components/Home/CommunicationSection.jsx
  src/components/Home/HeroSection.jsx
  src/components/Home/HomePageWrapper.jsx
  src/components/Home/RecentBlogsSection.jsx
  src/components/Home/TicketsSection.jsx
  src/components/Home/__test__/AppointementSection.test.js
  src/components/Home/__test__/AreYouCouncelor.test.js
  src/components/Home/__test__/CommunicationSection.test.js
  src/components/Home/__test__/HeroSection.test.js
  src/components/Home/__test__/HomePageWrapper.test.js
  src/components/Home/__test__/RecentBlogsSection.test.js
  src/components/Home/__test__/TicketsSection.test.js
  src/components/Home/__test__/__snapshots__/AppointementSection.test.js.snap
  src/components/Home/__test__/__snapshots__/AreYouCouncelor.test.js.snap
  src/components/Home/__test__/__snapshots__/CommunicationSection.test.js.snap
  src/components/Home/__test__/__snapshots__/HeroSection.test.js.snap
  src/components/Home/__test__/__snapshots__/HomePageWrapper.test.js.snap
  src/components/Home/__test__/__snapshots__/RecentBlogsSection.test.js.snap
  src/components/Home/__test__/__snapshots__/TicketsSection.test.js.snap
  src/components/Home/__test__/matchMedia.mock.js
  src/components/elements/Buttons/Button.jsx
  src/pages/index.jsx
  src/styles/globals.css
  src/util/library.js
  tailwind.config.js
  test-setup.js
Labels: enhancement, design, component, page, feature

#64 Creat the sign up page
  .husky/pre-commit
  package-lock.json
  package.json
  public/facebook.svg
  public/google.svg
  public/locales/ar/common.json
  public/locales/en/common.json
  public/signup.svg
  public/signupp.svg
  public/signuppp.svg
  src/components/Button.jsx
  src/components/Input.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/__test__/Navbar.test.js
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/Thankyou/SignupThanks.jsx
  src/components/Thankyou/__test__/Thankyou.test.js
  src/components/Thankyou/__test__/__snapshots__/Thankyou.test.js.snap
  src/context/context.js
  src/layout/Layout.jsx
  src/pages/_app.jsx
  src/pages/index.jsx
  src/pages/login/login.jsx
  src/pages/profile/profile.jsx
  src/pages/signUp/signUp.jsx
  src/util/firebase.js
Labels: enhancement, design, feature

#63 make careers page
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Button.jsx
  src/components/OpenPos.jsx
  src/pages/careers.jsx
Labels: enhancement, design, component, page

#67 add contact translation
  public/ContactUs.png
  public/locales/ar/common.json
  public/locales/en/common.json
  src/pages/contact.jsx
  src/pages/contactThankYou.jsx
Labels: bug, enhancement, design

#50 create about page
  public/locales/ar/common.json
  public/locales/en/common.json
  src/pages/About.jsx
Labels: enhancement, design

#73 62 therapist signup after successful form submission display a thank you page
  public/locales/ar/common.json
  public/locales/ar/therapists.json
  public/locales/en/common.json
  public/locales/en/therapists.json
  public/therapist.svg
  src/components/Input.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/pages/therapists/index.jsx
  src/pages/therapists/signup/index.jsx
Labels: firebase, authentication, feature
