Repository 202306-NEA-DZ-FEW/online-Therapist, pull requests merged in 2023-11, with the labels that each got.

#82 update user signup to use the user id
  src/context/AuthContext.js
  src/pages/login/login.jsx
  src/pages/signUp/index.jsx
Labels: enhancement, structure

#81 Creat payment methods page
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Cards/PaymentCard.jsx
  src/components/Cards/__test__/__snapshots__/PaymentCard.test.js.snap
  src/pages/paymentMethods/index.jsx
Labels: enhancement, page

#83 create multi step booking …
  next-i18next.config.js
  package.json
  public/locales/ar/booking.json
  public/locales/ar/login.json
  public/locales/en/booking.json
  public/locales/en/login.json
  src/components/Footer/index.jsx
  src/components/Home/AppointmentSection.jsx
  src/components/Home/HeroSection.jsx
  src/components/Home/__test__/__snapshots__/AppointementSection.test.js.snap
  src/components/Home/__test__/__snapshots__/HeroSection.test.js.snap
  src/components/Home/__test__/__snapshots__/HomePageWrapper.test.js.snap
  src/components/MutiStepBookingForm/BookingStep1.jsx
  src/components/MutiStepBookingForm/BookingStep2.jsx
  src/components/MutiStepBookingForm/BookingStep3.jsx
  src/components/MutiStepBookingForm/BookingStep4.jsx
  src/components/MutiStepBookingForm/BookingStep5.jsx
  src/components/MutiStepBookingForm/BookingStep6.jsx
  src/components/MutiStepBookingForm/BookingStep7.jsx
  src/components/MutiStepBookingForm/BookingStepFinal.jsx
  src/components/MutiStepBookingForm/MultiStepForm.jsx
  src/components/MutiStepBookingForm/__test__/BookingStep1.test.js
  src/components/MutiStepBookingForm/__test__/BookingStep2.test.js
  src/components/MutiStepBookingForm/__test__/BookingStep3.test.js
  src/components/MutiStepBookingForm/__test__/BookingStep4.test.js
  src/components/MutiStepBookingForm/__test__/BookingStep5.test.js
  src/components/MutiStepBookingForm/__test__/BookingStep6.test.js
  src/components/MutiStepBookingForm/__test__/BookingStep7.test.js
  src/components/MutiStepBookingForm/__test__/BookingStepFinal.test.js
  src/components/MutiStepBookingForm/__test__/MultiStepForm.test.js
  src/components/MutiStepBookingForm/__test__/__snapshots__/BookingStep1.test.js.snap
  src/components/MutiStepBookingForm/__test__/__snapshots__/BookingStep2.test.js.snap
  src/components/MutiStepBookingForm/__test__/__snapshots__/BookingStep3.test.js.snap
  src/components/MutiStepBookingForm/__test__/__snapshots__/BookingStep4.test.js.snap
  src/components/MutiStepBookingForm/__test__/__snapshots__/BookingStep5.test.js.snap
  src/components/MutiStepBookingForm/__test__/__snapshots__/BookingStep6.test.js.snap
  src/components/MutiStepBookingForm/__test__/__snapshots__/BookingStep7.test.js.snap
  src/components/MutiStepBookingForm/__test__/__snapshots__/BookingStepFinal.test.js.snap
  src/components/MutiStepBookingForm/__test__/__snapshots__/MultiStepForm.test.js.snap
  src/components/Navbar/Navbar.jsx
  src/components/elements/CheckboxInput.jsx
  src/components/elements/RadioInput.jsx
  src/components/elements/__test__/Button.test.js
  src/components/elements/__test__/CheckboxInput.test.js
  src/components/elements/__test__/Input.test.js
  src/components/elements/__test__/RadioInput.test.js
  src/components/elements/__test__/__snapshots__/Button.test.js.snap
  src/components/elements/__test__/__snapshots__/CheckboxInput.test.js.snap
  src/components/elements/__test__/__snapshots__/Input.test.js.snap
  src/components/elements/__test__/__snapshots__/RadioInput.test.js.snap
  src/pages/bookAnAppointment/index.jsx
  src/pages/login/login.jsx
Labels: design, structure, component, page, firebase, authentication

#85 refactor the code structure
  public/Images/Contact.jpg
  public/Images/ContactUs.png
  public/Images/Facebook.svg
  public/Images/Login.png
  public/Images/blog-img-placeholder.svg
  public/Images/chip.svg
  public/Images/close.svg
  public/Images/facebook.svg
  public/Images/google.svg
  public/Images/hamburger-menu.svg
  public/Images/login.svg
  public/Images/logo.png
  public/Images/mastercard.svg
  public/Images/signup.svg
  public/Images/therapist.svg
  public/Images/therapist1.png
  public/Images/visa.svg
  public/google.svg
  public/signup.svg
  src/components/Blog/SuggestedBlogsCard/__test__/Card.test.js
  src/components/Cards/BlogCard.jsx
  src/components/Cards/OpenPos.jsx
  src/components/Cards/PaymentCard.jsx
  src/components/Cards/TicketCard.jsx
  src/components/Cards/__test__/BlogCard.test.js
  src/components/Cards/__test__/OpenPos.test.js
  src/components/Cards/__test__/__snapshots__/BlogCard.test.js.snap
  src/components/Cards/__test__/__snapshots__/OpenPos.test.js.snap
  src/components/Cards/__test__/__snapshots__/PaymentCard.test.js.snap
  src/components/Cards/__test__/__snapshots__/TicketCard.test.js.snap
  src/components/Home/RecentBlogsSection.jsx
  src/components/Home/__test__/__snapshots__/HomePageWrapper.test.js.snap
  src/components/Home/__test__/__snapshots__/RecentBlogsSection.test.js.snap
  src/components/Home/__test__/__snapshots__/TicketsSection.test.js.snap
  src/components/Input.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/elements/Input.jsx
  src/components/elements/__test__/__snapshots__/Input.test.js.snap
  src/pages/about-us/index.jsx
  src/pages/careers/index.jsx
  src/pages/contact/contact.jsx
  src/pages/contact/contactThankYou.jsx
  src/pages/contact/index.jsx
  src/pages/contact/thankYou.jsx
  src/pages/login/index.jsx
  src/pages/requirements/index.jsx
  src/pages/sign-up/index.jsx
  src/pages/therapists/sign-up/index.jsx
  src/pages/userProfile/index.jsx
Labels: documentation, enhancement, structure

#93 Stripe Checkout Integration
  package-lock.json
  package.json
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Cards/TicketCard.jsx
  src/components/Cards/__test__/TicketCard.test.js
  src/components/Cards/__test__/__snapshots__/TicketCard.test.js.snap
  src/components/Home/TicketsSection.jsx
  src/components/Home/__test__/__snapshots__/HomePageWrapper.test.js.snap
  src/components/Home/__test__/__snapshots__/RecentBlogsSection.test.js.snap
  src/components/Home/__test__/__snapshots__/TicketsSection.test.js.snap
  src/pages/api/checkout_sessions/index.js
  src/pages/api/getproducts/index.js
  src/pages/api/getsingleproduct/[priceId].jsx
  src/pages/buyTicket/[priceId].jsx
  src/pages/success/index.jsx
Labels: enhancement, feature

#97 add therapist profile page
  .husky/pre-commit
  next.config.js
  package-lock.json
  package.json
  public/edit-profile.svg
  public/loading.svg
  public/locales/ar/therapists.json
  public/locales/en/therapists.json
  public/profile.png
  public/profile.svg
  public/profile1.png
  public/spinner.svg
  src/components/Profile/Input.jsx
  src/components/ProfileImage.jsx
  src/context/AuthContext.js
  src/layout/Layout.jsx
  src/pages/_app.jsx
  src/pages/test/index.jsx
  src/pages/therapists/profile/index.jsx
  src/pages/therapists/sign-up/index.jsx
  src/util/firebase.js
Labels: enhancement, design, feature

#94 create edit password page
  package-lock.json
  package.json
  public/locales/ar/common.json
  public/locales/ar/password.json
  public/locales/en/common.json
  public/locales/en/password.json
  src/pages/edit-password/index.jsx
Labels: page, authentication, feature

#96 Create add new credit card page
  package-lock.json
  package.json
  public/Images/MasterCard.png
  public/Images/VisaCard.png
  public/locales/ar/addnewcard.json
  public/locales/en/addnewcard.json
  src/components/Home/__test__/__snapshots__/AppointementSection.test.js.snap
  src/components/Home/__test__/__snapshots__/HeroSection.test.js.snap
  src/components/Home/__test__/__snapshots__/HomePageWrapper.test.js.snap
  src/components/MutiStepBookingForm/__test__/__snapshots__/BookingStep1.test.js.snap
  src/components/MutiStepBookingForm/__test__/__snapshots__/BookingStep2.test.js.snap
  src/components/MutiStepBookingForm/__test__/__snapshots__/BookingStep3.test.js.snap
  src/components/MutiStepBookingForm/__test__/__snapshots__/BookingStep4.test.js.snap
  src/components/MutiStepBookingForm/__test__/__snapshots__/BookingStep5.test.js.snap
  src/components/MutiStepBookingForm/__test__/__snapshots__/BookingStep6.test.js.snap
  src/components/MutiStepBookingForm/__test__/__snapshots__/BookingStep7.test.js.snap
  src/components/MutiStepBookingForm/__test__/__snapshots__/BookingStepFinal.test.js.snap
  src/components/MutiStepBookingForm/__test__/__snapshots__/MultiStepForm.test.js.snap
  src/components/Thankyou/__test__/__snapshots__/Thankyou.test.js.snap
  src/components/elements/Button.jsx
  src/components/elements/__test__/__snapshots__/Button.test.js.snap
  src/pages/addnewcard/index.js
Labels: design, component, page, feature

#104 Fetch the payment cards info from firestore
  public/locales/ar/common.json
  public/locales/en/common.json
  src/context/AuthContext.js
  src/pages/buyTicket/[priceId].jsx
  src/pages/paymentMethods/index.jsx
Labels: firebase, fetching data

#101 Favicon
  public/favicon.ico
  public/favicon1.ico
Labels: design

#102 Redesign 404 page
  package-lock.json
  package.json
  public/Images/404.svg
  public/Images/photo1.jpeg
  public/Images/photo2.jpeg
  public/Images/photo2.png
  public/fav.png
  public/favicon1.ico
  public/locales/ar/common.json
  public/locales/en/common.json
  src/pages/404.jsx
  src/pages/about-us/index.jsx
Labels: design

#105 Creat Dashboards for therapists and patients
  src/components/Dashboards/Links/Appointments.jsx
  src/components/Dashboards/Links/Calender.jsx
  src/components/Dashboards/Links/Messages.jsx
  src/components/Dashboards/Links/Patients.jsx
  src/components/Dashboards/Links/Therapists.jsx
  src/components/Dashboards/PatientDashboard.jsx
  src/components/Dashboards/ThearapistDashboard.jsx
  src/components/Dashboards/__test__/PatientDashboard.test.js
  src/components/Dashboards/__test__/TherapistDashboard.test.js
  src/components/Dashboards/__test__/__snapshots__/PatientDashboard.test.js.snap
  src/components/Dashboards/__test__/__snapshots__/TherapistDashboard.test.js.snap
  src/components/Navbar/dropdowns/UserDropdown.jsx
  src/components/Navbar/dropdowns/__test__/__snapshots__/UserDropdown.test.js.snap
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/__test__/Sidebar.test.js
  src/components/Sidebar/__test__/__snapshots__/Sidebar.test.js.snap
  src/context/AuthContext.js
  src/pages/dashboard/index.jsx
  src/util/library.js
Labels: enhancement, design

#106 add therapists and users appointments functionality.
  src/components/Home/AppointmentSection.jsx
  src/components/MutiStepBookingForm/MultiStepForm.jsx
  src/components/TherapistsAppointments/TherapistsAppointments.jsx
  src/pages/Appointments.jsx
  src/pages/therapists/index.jsx
  src/pages/therapists/sign-up/index.jsx
Labels: component, page, firebase, authentication, feature, fetching data

#108 Add functionality to contact page
  package-lock.json
  package.json
  src/pages/api/webhook/index.js
  src/pages/contact/index.jsx
  src/pages/contact/thankYou.jsx
  src/pages/success/index.jsx
Labels: enhancement, feature

#109 add blogs page, single blog page and embedded sanity studio
  .gitignore
  .husky/post-merge
  .npmrc
  netlify.toml
  next-i18next.config.js
  next.config.js
  next.lock/data/https_themer.sanity.build/api_hues_default_5f9ea1_darkest_001f24_primary_43b9b8_400_transparent_609da0_positive_43d675_300_caution_fbd024_200_lightest_fcfdfd_darkest_0d1516_6aeac73f30bd35e802c5
  next.lock/data/https_themer.sanity.build/api_hues_default_5f9ea1_primary_43b9b8_400_transparent_609da0_positive_43d675_300_caution_fbd024_200_lightest_fcfdfd_darkest_0d1516_6fe7a244150879fa5785
  next.lock/lock.json
  package-lock.json
  package.json
  public/locales/ar/blog.json
  public/locales/en/blog.json
  sanity.cli.js
  sanity.config.js
  sanity/env.js
  sanity/lib/client.js
  sanity/lib/image.js
  sanity/schema.js
  sanity/schemas/author.js
  sanity/schemas/blockContent.js
  sanity/schemas/category.js
  sanity/schemas/post.js
  src/context/AuthContext.js
  src/pages/blogs/[slug]/index.jsx
  src/pages/blogs/index.jsx
  src/pages/blogs/studio/[[...index]].jsx
  tailwind.config.js
Labels: design, page, firebase, authentication, feature, fetching data

#111 create about team page
  public/Images/member1.png
  public/Images/member2.png
  public/Images/member3.png
  public/Images/member4.png
  public/Images/member5.png
  public/Images/member6.png
  public/github.svg
  public/linkedin.svg
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Cards/TeamCard.jsx
  src/components/Cards/__test__/TeamCard.test.js
  src/pages/team/index.jsx
  src/util/library.js
Labels: enhancement, design, page

#115 Implement chat card
  src/components/Cards/ChatCard.jsx
  src/layout/Layout.jsx
Labels: enhancement, design, component

#114 Integrate Firestore to Manage User Tickets
  src/components/Cards/__test__/__snapshots__/TeamCard.test.js.snap
  src/context/AuthContext.js
  src/pages/api/checkout_sessions/index.js
  src/pages/api/webhook/index.js
  src/pages/buyTicket/[priceId].jsx
  src/pages/success/index.jsx
  src/pages/tickets/index.jsx
Labels: firebase, feature, fetching data

#120 Enhance the UI
  public/Images/18.jpg
  public/Images/20.jpg
  public/Images/member1.png
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Cards/CommunicationCard.jsx
  src/components/Cards/TicketCard.jsx
  src/components/Cards/__test__/__snapshots__/CommunicationCard.test.js.snap
  src/components/Cards/__test__/__snapshots__/TicketCard.test.js.snap
  src/components/Home/AppointmentSection.jsx
  src/components/Home/AreYouCouncelor.jsx
  src/components/Home/CommunicationSection.jsx
  src/components/Home/HeroSection.jsx
  src/components/Home/TicketsSection.jsx
  src/components/Home/__test__/__snapshots__/AppointementSection.test.js.snap
  src/components/Home/__test__/__snapshots__/AreYouCouncelor.test.js.snap
  src/components/Home/__test__/__snapshots__/CommunicationSection.test.js.snap
  src/components/Home/__test__/__snapshots__/HeroSection.test.js.snap
  src/components/Home/__test__/__snapshots__/HomePageWrapper.test.js.snap
  src/components/Home/__test__/__snapshots__/RecentBlogsSection.test.js.snap
  src/components/Home/__test__/__snapshots__/TicketsSection.test.js.snap
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/Navbar/dropdowns/AboutDropdown.jsx
  src/components/Navbar/dropdowns/LangDropdown.jsx
  src/components/Navbar/dropdowns/UserDropdown.jsx
  src/components/Navbar/dropdowns/__test__/__snapshots__/AboutDropdown.test.js.snap
  src/components/Navbar/dropdowns/__test__/__snapshots__/LangDropdown.test.js.snap
  src/components/Navbar/dropdowns/__test__/__snapshots__/UserDropdown.test.js.snap
  src/pages/about-us/index.jsx
  src/pages/contact/index.jsx
  src/pages/login/index.jsx
  src/pages/requirements/index.jsx
  src/pages/sign-up/index.jsx
Labels: enhancement, design

#122 Fix the bug of saving data and add some improvements
  public/locales/ar/users.json
  public/locales/en/users.json
  src/components/Home/TicketsSection.jsx
  src/components/Home/__test__/__snapshots__/HomePageWrapper.test.js.snap
  src/components/Home/__test__/__snapshots__/RecentBlogsSection.test.js.snap
  src/components/Home/__test__/__snapshots__/TicketsSection.test.js.snap
  src/components/Navbar/dropdowns/UserDropdown.jsx
  src/pages/login/index.jsx
  src/pages/profile/index.jsx
  src/pages/tickets/index.jsx
Labels: bug, enhancement, design, page, firebase, fetching data

#124 Enhancement of footer design
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Footer/DropDown.jsx
  src/components/Footer/__test__/__snapshots__/DropDown.test.js.snap
  src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
  src/components/Footer/index.jsx
  src/pages/profile/index.jsx
Labels: enhancement, design

#117 add reactions section and comments section
  next.config.js
  next.lock/data/https_themer.sanity.build/api_hues_default_5f9ea1_darkest_001f24_primary_43b9b8_400_transparent_609da0_positive_43d675_300_caution_fbd024_200_lightest_fcfdfd_darkest_0d1516_6aeac73f30bd35e802c5
  next.lock/data/https_themer.sanity.build/api_hues_default_5f9ea1_primary_43b9b8_400_transparent_609da0_positive_43d675_300_caution_fbd024_200_lightest_fcfdfd_darkest_0d1516_6fe7a244150879fa5785
  next.lock/lock.json
  public/locales/ar/blog.json
  public/locales/en/blog.json
  sanity/schema.js
  sanity/schemas/comment.js
  sanity/schemas/reaction.js
  src/components/Blog/AddComment.jsx
  src/components/Blog/Comments.jsx
  src/components/Blog/Reactions.jsx
  src/components/ProfileImage.jsx
  src/context/AuthContext.js
  src/layout/Layout.jsx
  src/pages/api/blog/create-comment.js
  src/pages/api/blog/reactions.js
  src/pages/blogs/[slug]/index.jsx
  src/pages/blogs/index.jsx
  src/pages/therapists/profile/index.jsx
Labels: enhancement, design, page, feature, fetching data

#126 fix blogs section in homepage and navbar items
  public/locales/ar/homepage.json
  public/locales/en/homepage.json
  src/components/Cards/BlogCard.jsx
  src/components/Cards/__test__/__snapshots__/BlogCard.test.js.snap
  src/components/Home/HomePageWrapper.jsx
  src/components/Home/RecentBlogsSection.jsx
  src/components/Home/__test__/RecentBlogsSection.test.js
  src/components/Home/__test__/__snapshots__/HomePageWrapper.test.js.snap
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/ProfileImage.jsx
  src/pages/index.jsx
Labels: bug, enhancement

#129 Adjust the responsiveness for the user profile and fix links
  public/Images/logo2.png
  public/locales/ar/users.json
  public/locales/en/users.json
  src/components/Dashboards/__test__/__snapshots__/PatientDashboard.test.js.snap
  src/components/Dashboards/__test__/__snapshots__/TherapistDashboard.test.js.snap
  src/components/Sidebar/__test__/__snapshots__/Sidebar.test.js.snap
  src/pages/profile/index.jsx
  src/util/library.js
Labels: bug, enhancement, design

#131 Add translation to the dashboard
  public/Images/logo2.png
  public/locales/ar/dashboard.json
  public/locales/en/dashboard.json
  src/components/Dashboards/Links/PatientAppointments.jsx
  src/components/Dashboards/Links/Patients.jsx
  src/components/Dashboards/Links/TherapistAppointments.jsx
  src/components/Dashboards/Links/Therapists.jsx
  src/components/Dashboards/Links/WaitingAppointments.jsx
  src/components/Dashboards/Links/__test__/__snapshots__/PatientAppointments.test.js.snap
  src/components/Dashboards/Links/__test__/__snapshots__/Patients.test.js.snap
  src/components/Dashboards/Links/__test__/__snapshots__/TherapistAppointments.test.js.snap
  src/components/Dashboards/Links/__test__/__snapshots__/Therapists.test.js.snap
  src/components/Dashboards/Links/__test__/__snapshots__/WaitingAppointments.test.js.snap
  src/components/Dashboards/__test__/__snapshots__/PatientDashboard.test.js.snap
  src/components/Dashboards/__test__/__snapshots__/TherapistDashboard.test.js.snap
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/__test__/__snapshots__/Sidebar.test.js.snap
  src/pages/dashboard/index.jsx
  src/util/library.js
Labels: enhancement

#135 Creat a tickets collection in firestore
  src/context/AuthContext.js
  src/pages/buyTicket/[priceId].jsx
  src/pages/success/index.jsx
Labels: firebase

#138 remove arrows from homepage slider
  src/components/Home/RecentBlogsSection.jsx
  src/layout/Layout.jsx
Labels: bug, enhancement

#137 Save information to firestore in google sign up
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Cards/TeamCard.jsx
  src/components/Cards/__test__/__snapshots__/TeamCard.test.js.snap
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/context/AuthContext.js
  src/pages/sign-up/index.jsx
Labels: enhancement, firebase

#140 fix ProfileImage and some styling
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/ProfileImage.jsx
  src/context/AuthContext.js
  src/pages/blogs/index.jsx
Labels: bug, component
